---
title: "`r paste(params$species, params$genome_folder, 'Create Tree')`"
date: "`r format(Sys.Date(), '%B %d, %Y')`"
author: "Maddie Krieger"
output: html_document
params:
  project: "003"
  tree_name: "mashtree"
  outgroup: "GCF_003172975"
  tree_metadata: "project003_metadata.csv"
editor_options: 
  markdown: 
    wrap: sentence
---

Load libraries
```{r}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

library(ape)
library(ggtree)
library(tidyverse)

project_id <- params$project
tree_name <- params$tree_name
outgroup <- params$outgroup
tree_metadata <- params$tree_metadata

output_dir <- paste0("../outputs/", project_id, "/anvio/tree/ggtree_figs")
if (!dir.exists(output_dir)) {
  dir.create(output_dir, recursive = TRUE)
}

tree_metadata <- if (tree_metadata != "") {
  read_csv(paste0("../tree_metadata/", tree_metadata, ".csv"))
} else {
  NULL
}

```


Load files
```{r}
tree_file <- paste0("../outputs/", project_id, "/anvio/tree/", tree_name, ".nwk")
tree <- read.tree(tree_file)
tree
```

Clean up tip labels from the reference
```{r}
tree$tip.label <- ifelse(
  str_detect(tree$tip.label, "^GCF"),
  str_extract(tree$tip.label, "^GCF_[0-9]+"),
  tree$tip.label
)
tree$tip.label <- gsub("_contigs", "", tree$tip.label)

tree$tip.label
```

```{r}
tree_rooted <- root(tree, outgroup = outgroup, resolve.root = TRUE)
```


```{r}
tips <- tibble(label = tree_rooted$tip.label) %>%
  mutate(
    type = case_when(
      str_detect(label, outgroup) ~ "Outgroup",
      str_detect(label, "GCF")      ~ "Reference",
      TRUE                          ~ "WGS"
    )
  )

tips
```


```{r, fig.width=5, fig.height=25}

p <- ggtree(tree_rooted) %<+% tips +
  geom_tiplab(aes(color = type), size = 3) +
  scale_color_manual(
    values = c(
      "WGS"      = "red",
      "Outgroup" = "black",
      "Reference" = "blue"
    )) +
  theme_tree2() +
  xlim_tree(1) +  # add extra space on the right (increase if needed)
  theme(legend.position = "right")

p

ggsave(filename=paste0(output_dir, "/", tree_name, "_tree.png"),
       plot=p,
       width=5,
       height=8,
       units="in",
       dpi=300)
```




